export enum Aisle {
  ALCOHOL = "alcohol",
  BAKING = "baking",
  BEVERAGE = "beverage",
  BREAD = "bread",
  BREAKFAST = "breakfast",
  CANDY = "candy",
  CANNED = "canned",
  CHEESE = "cheese",
  BUTTER = "butter",
  CONDIMENT = "condiment",
  DAIRY = "dairy",
  DELI = "deli",
  FRUITS = "fruits",
  GLUTEN_FREE = "gluten-free",
  HERBS = "herbs",
  MEAT = "meat",
  SEAFOOD = "seafood",
  ORGANIC = "organic",
  PAPER = "paper",
  CLEANING = "cleaning",
  SNACK = "snack",
  PASTA = "pasta",
} 